"use client";
import type { ProjectDetail } from "@/services/project-detail";
import type { CifProjectDossier } from "@/services/cif-loader";

/**
 * Due-diligence memo — print-friendly export (§2b: one-click exportable
 * deliverable). Window print → Save as PDF. Light theme on purpose.
 */
export function PrintMemo({ detail, cif }: { detail: ProjectDetail; cif: CifProjectDossier | null }) {
  const d = detail;
  return (
    <div className="min-h-screen bg-white p-8 font-sans text-[13px] leading-relaxed text-black">
      <button
        className="fixed right-4 top-4 rounded-md border border-black/20 px-3 py-1.5 text-xs hover:bg-black/5 print:hidden"
        onClick={() => window.print()}
      >
        🖨 Print / Save PDF
      </button>

      <header className="border-b-2 border-black pb-3">
        <div className="text-[10px] uppercase tracking-widest text-black/60">INTENT — due-diligence memo</div>
        <h1 className="mt-1 text-2xl font-bold">{d.project.name}</h1>
        <div className="text-xs text-black/60">
          {d.project.category} · {d.project.tokenSymbol ?? "no token"} · generated {new Date().toISOString().slice(0, 10)} · research-completeness {cif?.qa ? `${cif.qa.total.toFixed(1)}/100` : "n/a (not a research-completeness verdict on the project)"}
        </div>
      </header>

      <section className="mt-4">
        <h2 className="text-sm font-bold uppercase tracking-wide">1 · Context & telemetry</h2>
        <p className="mt-1">{d.project.description}</p>
        <p className="mt-1 text-xs">
          TVL {fmt(d.project.tvlUsd)} · Vol 24h {fmt(d.project.volume24hUsd)} · 30d TVL {d.project.tvl30dPct >= 0 ? "+" : ""}
          {d.project.tvl30dPct}% · sentiment {d.project.sentiment.toFixed(2)}
        </p>
      </section>

      {cif?.decisionEvents && cif.decisionEvents.length > 0 && (
        <section className="mt-4">
          <h2 className="text-sm font-bold uppercase tracking-wide">2 · Decision events (causal chain)</h2>
          {cif.decisionEvents.map((de, i) => (
            <div key={i} className="mt-2 break-inside-avoid rounded border border-black/15 p-2">
              <div className="text-xs font-semibold">{de.date} — {de.title}</div>
              <p className="text-xs"><strong>Decision:</strong> {de.decision}</p>
              <p className="text-xs"><strong>Trigger:</strong> {de.trigger}</p>
              <p className="text-xs"><strong>Short-term:</strong> {de.immediate_result}</p>
              <p className="text-xs"><strong>Long-term:</strong> {de.long_term_impact}</p>
            </div>
          ))}
        </section>
      )}

      {cif?.qa && (
        <section className="mt-4">
          <h2 className="text-sm font-bold uppercase tracking-wide">3 · Research completeness (Intent Score — NOT project health)</h2>
          <table className="mt-1 w-full text-xs">
            <tbody>
              {cif.qa.dimensions.map((dim) => (
                <tr key={dim.key} className="border-b border-black/10">
                  <td className="py-0.5 pr-2">{dim.label} (w{dim.weight})</td>
                  <td className="py-0.5 text-right font-mono">{dim.score.toFixed(0)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </section>
      )}

      {cif?.conflicts && cif.conflicts.length > 0 && (
        <section className="mt-4">
          <h2 className="text-sm font-bold uppercase tracking-wide">4 · Cross-checked conflicts</h2>
          {cif.conflicts.map((c) => (
            <p key={c.id} className="mt-1 text-xs">
              <strong>{c.title}</strong> [{c.severity} · {c.status}] — {c.description} A: {c.versionA.source} {c.versionA.value}; B: {c.versionB.source} {c.versionB.value}.
            </p>
          ))}
        </section>
      )}

      {cif?.knowledge && cif.knowledge.length > 0 && (
        <section className="mt-4">
          <h2 className="text-sm font-bold uppercase tracking-wide">5 · Key knowledge (with citations)</h2>
          {cif.knowledge.slice(0, 8).map((k) => (
            <p key={k.id} className="mt-1 text-xs">
              • {k.name} — {k.description} <span className="text-black/50">[{k.evidenceText?.slice(0, 120)}]</span>
            </p>
          ))}
        </section>
      )}

      <footer className="mt-6 border-t border-black/20 pt-2 text-[10px] text-black/60">
        Generated by INTENT. Every claim traces to the locked INTENT dossier (examples/CaseStudies). This memo is an input to your own decision — not investment advice.
      </footer>
    </div>
  );
}

function fmt(n: number): string {
  if (Math.abs(n) >= 1e9) return `$${(n / 1e9).toFixed(2)}B`;
  if (Math.abs(n) >= 1e6) return `$${(n / 1e6).toFixed(1)}M`;
  if (Math.abs(n) >= 1e3) return `$${(n / 1e3).toFixed(0)}K`;
  return `$${n.toFixed(0)}`;
}
